### ISSUE TITLE
Validation passes for invalid input

### ISSUE THREAD

**Issue by kevgathuku** [ireade/form-validation-realtime#7]
Hi, 
I've been trying the validation on the demo page and I am experiencing a few bugs.
For example, the username field passes validation even if there are invalid characters, as long as the length is longer than 3
See the attached screenshot for an example of this 
<img width="671" alt="screen shot 2016-07-07 at 10 54 01 am" src="https://cloud.githubusercontent.com/assets/3721994/16646150/414956d0-4431-11e6-94ba-720887e2412a.png">

**Comment by ireade** [comment]
Hi @kevgathuku . Thanks for letting me know, was an issue with a previous PR. I've fixed it now.

**Comment by kevgathuku** [comment]
Awesome 👍
